export const INDUSTRIES = [
  "Technology",
  "Finance & Banking",
  "Healthcare",
  "Retail & E-commerce",
  "Manufacturing",
  "Education",
  "Media & Entertainment",
  "Government & Public Sector",
  "Non-profit",
  "Consulting & Professional Services",
  "Real Estate",
  "Transportation & Logistics",
  "Food & Beverage",
  "Energy & Utilities",
  "Telecommunications",
  "Other",
];
